# Generated by Django 5.2 on 2025-04-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='reps',
            new_name='set1_reps',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='sets',
            new_name='set2_reps',
        ),
        migrations.AddField(
            model_name='workout',
            name='set3_reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
