# Generated by Django 5.2 on 2025-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='session_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
